name: Hello Example

on:
  workflow_dispatch:  # lets you run it manually from GitHub

jobs:
  run-hello:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Run my script
        run: python hello.py
